const res = {
    method: 'POST',
    url: 'https://messenger-plum-eight.vercel.app/api/webhooks',
    headers: Headers {
      accept: '*/*',
      'accept-encoding': 'gzip',
      connection: 'close',
      'content-length': '596',
      'content-type': 'application/json',
      forwarded: 'for=54.216.8.72;host=messenger-plum-eight.vercel.app;proto=https;sig=0QmVhcmVyIGNkMDg2ODEzZWZmNDhiZGU3MDVhMjViYWZlODEyOGZlM2JjYTY4MmY3NmMxNTk5OGYzM2QxMTQ4ZjA2ZGJkNGY=;exp=1720713092',
      host: 'messenger-plum-eight.vercel.app',
      'svix-id': 'msg_2j6g9wlHW6awuuqi2nANhO8MJ4o',
      'svix-signature': 'v1,QQy11UFWoQgFgwMdKexPnXgdxYxkak44m0coCOeECxM=',
      'svix-timestamp': '1720712792',
      'user-agent': 'Svix-Webhooks/1.24.0',
      'x-clerk-auth-message': '',
      'x-clerk-auth-reason': 'dev-browser-missing',
      'x-clerk-auth-signature': '',
      'x-clerk-auth-status': 'signed-out',
      'x-clerk-auth-token': '',
      'x-clerk-clerk-url': 'https://messenger-plum-eight.vercel.app/api/webhooks',
      'x-forwarded-for': '54.216.8.72',
      'x-forwarded-host': 'messenger-plum-eight.vercel.app',
      'x-forwarded-port': '443',
      'x-forwarded-proto': 'https',
      'x-matched-path': '/api/webhooks',
      'x-real-ip': '54.216.8.72',
      'x-vercel-deployment-url': 'messenger-7ph9o31ns-david-wissehs-projects.vercel.app',
      'x-vercel-forwarded-for': '54.216.8.72',
      'x-vercel-id': 'dub1::79vmq-1720712792639-ecd7d2f7f105',
      'x-vercel-ip-as-number': '16509',
      'x-vercel-ip-city': 'Dublin',
      'x-vercel-ip-continent': 'EU',
      'x-vercel-ip-country': 'IE',
      'x-vercel-ip-country-region': 'L',
      'x-vercel-ip-latitude': '53.3379',
      'x-vercel-ip-longitude': '-6.2591',
      'x-vercel-ip-timezone': 'Europe/Dublin',
      'x-vercel-ja4-digest': 't13d311100_e8f1e7e78f70_d41ae481755e',
      'x-vercel-proxied-for': '54.216.8.72',
      'x-vercel-proxy-signature': 'Bearer cd086813eff48bde705a25bafe8128fe3bca682f76c15998f33d1148f06dbd4f',
      'x-vercel-proxy-signature-ts': '1720713092',
      'x-vercel-sc-basepath': '',
      'x-vercel-sc-headers': '{"Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXBsb3ltZW50SWQiOiJkcGxfR3VTNFpoU1U5WVdWVVE4a0JqZlRnZGtrMnk0USIsInVubGltaXRlZCI6ZmFsc2UsInBsYW4iOiJob2JieSIsImRvbWFpbiI6Im1lc3Nlbmdlci1wbHVtLWVpZ2h0LnZlcmNlbC5hcHAiLCJibG9jayI6ZmFsc2UsImlhdCI6MTcyMDcxMjc5MywicHJvamVjdElkIjoicHJqX1BjTU5RNGN4a0JjTmdBZHJsTnFpTXJsRFJLajgiLCJleHAiOjE3MjA3MTM3MTMsIm93bmVySWQiOiJ0ZWFtX2Z6dk5BV3pwelNkeHZtOHhacmVzUTh1dCIsInJlcXVlc3RJZCI6Ijc5dm1xLTE3MjA3MTI3OTI2MzktZWNkN2QyZjdmMTA1IiwiZW52IjoicHJvZHVjdGlvbiJ9.fxnUKELmPKxjelvwvFt3Q0TZrWZc7vbNeKWOpsA4qN8"}',
      'x-vercel-sc-host': 'iad1.suspense-cache.vercel-infra.com'
    },
    destination: '',
    referrer: 'about:client',
    referrerPolicy: '',
    mode: 'cors',
    credentials: 'same-origin',
    cache: 'default',
    redirect: 'follow',
    integrity: '',
    keepalive: false,
    isReloadNavigation: false,
    isHistoryNavigation: false,
    signal: AbortSignal { aborted: false }
  }

  