import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { firebaseConfig } from "@/util/util";

import { Toaster } from "@/components/ui/toaster";
import { initializeApp, getApp } from "firebase/app";

const inter = Inter({ subsets: ["latin"] });
const serviceAccount = JSON.parse(process.env.SERVICE_ACCOUNT!);
let s = null;
try {
  s = getApp();
} catch (err) {
  console.error(err);
}
if (!s) {
  initializeApp({
    ...firebaseConfig,
    databaseURL: "https://messenger-fdf1b.nam5.firebaseio.com",
  });
  console.log("Initialized App");
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className=" dark:bg-black">
        <body className={inter.className}>
          {children}

          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
